<a href="https://colab.research.google.com/github/6RobinLiu/PytorchDL/blob/main/PytorchBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 69.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 55.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 40.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 79.2 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [3]:
import torch
tensor1=torch.tensor([[1,2,3],[4,5,6]])
tensor1.shape

torch.Size([2, 3])

In [4]:
tensor=torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


In [5]:
import numpy as np

array=np.zeros((5,5))
type(array)

numpy.ndarray

In [6]:
tensor=torch.from_numpy(array)
type(tensor)

torch.Tensor

# Tensor Math and Comparison

In [7]:
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

z1=x+y
z2=x-y

z=torch.true_divide(x,y)

t=torch.zeros(3)
t.add_(x)
z1,z2,z,t

(tensor([10, 10, 10]),
 tensor([-8, -6, -4]),
 tensor([0.1111, 0.2500, 0.4286]),
 tensor([1., 2., 3.]))

上面的这个加法表示原来的int类型的tensor加上浮点类型的0向量，就变成了浮点类型的tensor

也就是做了一次类型转换

并且使用的是add_() 也就是原地的加法   没有产生新的变量  如t=t+x
```
x = torch.tensor([1, 2, 3])
t = x.float()

```
上述就是直接的类型转换

- 在训练模型、调试、实验阶段  尽量不要使用原地的加法，这样兼容autograd 也不容易出bug
- 在部署 优化  或者又大量的tensor加减中 可以使用原地的加法，加快速度

下面是一个测试的例子

演示了时间的快慢



In [8]:
import time

x = torch.rand(10000)
y = torch.rand(10000)

# 非原地
start = time.time()
for _ in range(10000):
    z = x + y
print("非原地耗时:", time.time() - start)

# 原地
z = torch.zeros(10000)
start = time.time()
for _ in range(10000):
    z.add_(x)
print("原地耗时:", time.time() - start)

非原地耗时: 0.20708751678466797
原地耗时: 0.08061909675598145


In [9]:
# 指数运算
x=torch.tensor([1,2,3])
z1=x.pow(2)
z2=x**2
z1,z2

(tensor([1, 4, 9]), tensor([1, 4, 9]))

In [10]:
#矩阵乘法
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2)
x3=x1.mm(x2)
x3

tensor([[1.6967, 1.9975, 1.3636],
        [1.1354, 0.8744, 0.7160]])

In [11]:
#矩阵乘方
matrix=torch.rand(5,5)
matrix.matrix_power(3)

tensor([[2.0009, 3.4415, 2.9471, 1.7796, 2.1576],
        [1.7306, 3.0893, 2.6046, 1.5700, 1.8578],
        [2.0984, 3.6532, 3.1464, 1.8484, 2.2746],
        [2.0478, 3.5922, 3.0799, 1.8402, 2.2303],
        [3.6261, 6.4268, 5.4484, 3.2397, 3.9177]])

In [12]:
#依次相乘
x1=torch.tensor([1,2,3])
x2=torch.tensor([4,5,6])
z=x1*x2
z

tensor([ 4, 10, 18])

In [13]:
# 点积
z=torch.dot(x1,x2)
z

tensor(32)

In [14]:
# 批矩阵相乘
batch=32
m=10
n=20
p=30

tensor1=torch.rand((batch,m,n))
tensor2=torch.rand((batch,n,p))
tensor=torch.bmm(tensor1,tensor2)  # batch 乘
tensor.shape


torch.Size([32, 10, 30])

# 其他

In [15]:
x1=torch.rand((5,5))
x2=torch.rand((1,5))

z1=x1-x2
z2=x1**x2
x1,x2,z1,z2

(tensor([[0.3779, 0.2753, 0.2769, 0.5905, 0.8402],
         [0.6845, 0.9392, 0.0452, 0.0543, 0.3886],
         [0.8359, 0.5948, 0.8032, 0.6136, 0.3189],
         [0.4625, 0.6930, 0.6307, 0.1804, 0.8149],
         [0.4709, 0.9123, 0.8997, 0.8660, 0.4424]]),
 tensor([[0.1031, 0.5260, 0.6549, 0.3517, 0.6105]]),
 tensor([[ 0.2747, -0.2507, -0.3780,  0.2387,  0.2297],
         [ 0.5813,  0.4132, -0.6097, -0.2975, -0.2219],
         [ 0.7327,  0.0688,  0.1484,  0.2619, -0.2916],
         [ 0.3594,  0.1670, -0.0242, -0.1713,  0.2044],
         [ 0.3678,  0.3863,  0.2448,  0.5142, -0.1681]]),
 tensor([[0.9045, 0.5074, 0.4313, 0.8308, 0.8992],
         [0.9617, 0.9675, 0.1316, 0.3589, 0.5616],
         [0.9817, 0.7609, 0.8663, 0.8422, 0.4977],
         [0.9236, 0.8246, 0.7395, 0.5475, 0.8825],
         [0.9253, 0.9529, 0.9331, 0.9506, 0.6078]]))

这里的x2实际上就是在做运算时  把每一行复制一份

这个也叫  广播机制

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])
sum1=torch.sum(x)
sum2=torch.sum(x,dim=0)
sum3=torch.sum(x,dim=1)
sum1,sum2,sum3

(tensor(21), tensor([5, 7, 9]), tensor([ 6, 15]))

dim控制的是在哪个维度上聚合
dim=0  就是沿着第0维压缩  也就是列求和
dim=1  就是沿着第1维压缩  也就是行求和
.....

dim与tensor的维度有关

$$
-rank<=dim<rank$$

若shape是(2,3,4) dim可取0,1,2,-1,-2,-3


复数表示倒数第几个维度

In [17]:
x=torch.rand(5,5)
values,indices=torch.max(x,dim=0)
x,values,indices
# dim=0表示每列最大值    dim=1表示每行最小值

(tensor([[0.2575, 0.0887, 0.9762, 0.0736, 0.7991],
         [0.2353, 0.5906, 0.6285, 0.2329, 0.3514],
         [0.2986, 0.0818, 0.0987, 0.1556, 0.6180],
         [0.6648, 0.1028, 0.1508, 0.8625, 0.7650],
         [0.7352, 0.2957, 0.9733, 0.1524, 0.3063]]),
 tensor([0.7352, 0.5906, 0.9762, 0.8625, 0.7991]),
 tensor([4, 1, 0, 3, 0]))

In [18]:
abs_x=torch.abs(x)  #求绝对值

z=torch.argmax(x,dim=0)  # 最大值的位置
x,z

(tensor([[0.2575, 0.0887, 0.9762, 0.0736, 0.7991],
         [0.2353, 0.5906, 0.6285, 0.2329, 0.3514],
         [0.2986, 0.0818, 0.0987, 0.1556, 0.6180],
         [0.6648, 0.1028, 0.1508, 0.8625, 0.7650],
         [0.7352, 0.2957, 0.9733, 0.1524, 0.3063]]),
 tensor([4, 1, 0, 3, 0]))

In [19]:
mean=torch.mean(x.float(),dim=0)

In [20]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])

z=torch.eq(x,y)
z  #判断是否一样

tensor([False, False, False])

In [21]:
x=torch.tensor([-1,-2,3,4,5])
z=torch.clamp(x,min=0)
z
# 表示小于0的都置0  其他的不管

tensor([0, 0, 3, 4, 5])

In [22]:
x=torch.tensor([0,1,0,1,1],dtype=torch.bool)
z1=torch.any(x)   #有一个是 1 的就可以
z2=torch.all(x)   #必须要所有的都是 1
z1,z2

(tensor(True), tensor(False))

# Tensor Indexing


In [23]:
batch_size=10
features=25

x=torch.rand(batch_size,features)
x[0].shape,x[:,0].shape

x[2,0:10]

tensor([0.9527, 0.8816, 0.6895, 0.0403, 0.2704, 0.3468, 0.1444, 0.8158, 0.5989,
        0.0930])

In [24]:
# Fancy Indexing
x=torch.arange(10)
indices=[2,5,8]
x[indices]

tensor([2, 5, 8])

In [25]:
x=torch.rand(3,5)
rows=torch.tensor([1,0])
cols=torch.tensor([4,0])
x,x[rows,cols]
#一种高级索引  分别给出需要取得点的  行标和列标

(tensor([[0.7304, 0.3942, 0.1346, 0.0016, 0.8795],
         [0.7953, 0.6086, 0.2094, 0.3586, 0.2272],
         [0.5158, 0.2353, 0.4928, 0.8655, 0.0060]]),
 tensor([0.2272, 0.7304]))

In [26]:
#useful operation
x=torch.tensor([0,1,0,3,3,2,2,4,3,4])
x.unique()

tensor([0, 1, 2, 3, 4])

# Tensor Reshape


In [28]:
x=torch.arange(9)
x1=x.view(3,3)
x2=x.reshape(3,3)
x1,x2

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [31]:
x1=torch.rand(3,3)
x2=torch.rand(3,3)
x=torch.cat((x1,x2),dim=0)
y=torch.cat((x1,x2),dim=1)
x1,x2,x,y

(tensor([[0.5352, 0.9502, 0.6725],
         [0.8349, 0.3918, 0.6584],
         [0.8702, 0.0677, 0.8869]]),
 tensor([[0.8205, 0.7790, 0.7067],
         [0.5696, 0.6717, 0.9729],
         [0.4971, 0.1718, 0.6396]]),
 tensor([[0.5352, 0.9502, 0.6725],
         [0.8349, 0.3918, 0.6584],
         [0.8702, 0.0677, 0.8869],
         [0.8205, 0.7790, 0.7067],
         [0.5696, 0.6717, 0.9729],
         [0.4971, 0.1718, 0.6396]]),
 tensor([[0.5352, 0.9502, 0.6725, 0.8205, 0.7790, 0.7067],
         [0.8349, 0.3918, 0.6584, 0.5696, 0.6717, 0.9729],
         [0.8702, 0.0677, 0.8869, 0.4971, 0.1718, 0.6396]]))

In [32]:
# permute置换维度
x=torch.rand(32,3,224,224) #假设分别就代表   batch_size channels height  width
x=x.permute(0,2,3,1)
x.shape

torch.Size([32, 224, 224, 3])