<a href="https://colab.research.google.com/github/6RobinLiu/PytorchDL/blob/main/PytorchBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 68.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 60.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 52.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 80.0 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [3]:
import torch
tensor1=torch.tensor([[1,2,3],[4,5,6]])
tensor1.shape

torch.Size([2, 3])

In [4]:
tensor=torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


In [7]:
import numpy as np

array=np.zeros((5,5))
type(array)

numpy.ndarray

In [8]:
tensor=torch.from_numpy(array)
type(tensor)

torch.Tensor

# Tensor Math and Comparison

In [9]:
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

z1=x+y
z2=x-y

z=torch.true_divide(x,y)

t=torch.zeros(3)
t.add_(x)
z1,z2,z,t

(tensor([10, 10, 10]),
 tensor([-8, -6, -4]),
 tensor([0.1111, 0.2500, 0.4286]),
 tensor([1., 2., 3.]))

上面的这个加法表示原来的int类型的tensor加上浮点类型的0向量，就变成了浮点类型的tensor

也就是做了一次类型转换

并且使用的是add_() 也就是原地的加法   没有产生新的变量  如t=t+x
```
x = torch.tensor([1, 2, 3])
t = x.float()

```
上述就是直接的类型转换

- 在训练模型、调试、实验阶段  尽量不要使用原地的加法，这样兼容autograd 也不容易出bug
- 在部署 优化  或者又大量的tensor加减中 可以使用原地的加法，加快速度

下面是一个测试的例子

演示了时间的快慢



In [10]:
import time

x = torch.rand(10000)
y = torch.rand(10000)

# 非原地
start = time.time()
for _ in range(10000):
    z = x + y
print("非原地耗时:", time.time() - start)

# 原地
z = torch.zeros(10000)
start = time.time()
for _ in range(10000):
    z.add_(x)
print("原地耗时:", time.time() - start)

非原地耗时: 0.044324636459350586
原地耗时: 0.028002500534057617


In [13]:
# 指数运算
x=torch.tensor([1,2,3])
z1=x.pow(2)
z2=x**2
z1,z2

(tensor([1, 4, 9]), tensor([1, 4, 9]))

In [15]:
#矩阵乘法
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2)
x3=x1.mm(x2)
x3

tensor([[1.3174, 1.3572, 2.0672],
        [0.2600, 0.4299, 0.5847]])

In [16]:
#矩阵乘方
matrix=torch.rand(5,5)
matrix.matrix_power(3)

tensor([[7.5382, 4.0905, 7.3241, 4.8646, 7.3105],
        [9.2549, 4.9996, 9.0124, 5.9450, 8.9951],
        [3.4208, 1.8763, 3.2965, 2.2322, 3.3127],
        [6.1190, 3.2965, 6.0144, 3.8785, 5.9036],
        [4.5084, 2.4745, 4.4193, 2.8865, 4.2907]])

In [18]:
#依次相乘
x1=torch.tensor([1,2,3])
x2=torch.tensor([4,5,6])
z=x1*x2
z

tensor([ 4, 10, 18])

In [20]:
# 点积
z=torch.dot(x1,x2)
z

tensor(32)

In [23]:
# 批矩阵相乘
batch=32
m=10
n=20
p=30

tensor1=torch.rand((batch,m,n))
tensor2=torch.rand((batch,n,p))
tensor=torch.bmm(tensor1,tensor2)  # batch 乘
tensor.shape


torch.Size([32, 10, 30])

# Broadcasting 广播机制


In [28]:
x1=torch.rand((5,5))
x2=torch.rand((1,5))

z1=x1-x2
z2=x1**x2
x1,x2,z1,z2

(tensor([[0.7631, 0.4519, 0.6684, 0.3246, 0.2150],
         [0.4900, 0.1436, 0.5120, 0.7077, 0.3886],
         [0.0078, 0.9611, 0.9459, 0.9506, 0.3970],
         [0.4680, 0.2249, 0.1659, 0.4853, 0.1435],
         [0.1322, 0.4653, 0.5132, 0.5227, 0.0317]]),
 tensor([[0.3453, 0.8475, 0.3269, 0.3263, 0.6010]]),
 tensor([[ 0.4178, -0.3956,  0.3415, -0.0017, -0.3860],
         [ 0.1447, -0.7039,  0.1850,  0.3814, -0.2124],
         [-0.3375,  0.1135,  0.6190,  0.6243, -0.2040],
         [ 0.1227, -0.6226, -0.1611,  0.1590, -0.4575],
         [-0.2131, -0.3823,  0.1863,  0.1964, -0.5694]]),
 tensor([[0.9109, 0.5101, 0.8766, 0.6927, 0.3970],
         [0.7817, 0.1930, 0.8034, 0.8933, 0.5666],
         [0.1869, 0.9669, 0.9820, 0.9836, 0.5740],
         [0.7694, 0.2824, 0.5558, 0.7898, 0.3114],
         [0.4973, 0.5228, 0.8041, 0.8092, 0.1255]]))

这里的x2实际上就是在做运算时  把每一行复制一份

In [35]:
x=torch.tensor([[1,2,3],[4,5,6]])
sum1=torch.sum(x)
sum2=torch.sum(x,dim=0)
sum3=torch.sum(x,dim=1)
sum1,sum2,sum3

(tensor(21), tensor([5, 7, 9]), tensor([ 6, 15]))

dim控制的是在哪个维度上聚合
dim=0  就是沿着第0维压缩  也就是列求和
dim=1  就是沿着第1维压缩  也就是行求和
.....

dim与tensor的维度有关

$$
-rank<=dim<rank$$

若shape是(2,3,4) dim可取0,1,2,-1,-2,-3


复数表示倒数第几个维度