<a href="https://colab.research.google.com/github/6RobinLiu/PytorchLearn/blob/main/Tensorlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 78.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 59.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 40.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 90.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [2]:
import torch

a=[1,2,3.]
type(a)

list

In [3]:
b=torch.tensor(a)
b

tensor([1., 2., 3.])

In [4]:
b.dtype,type(b)

(torch.float32, torch.Tensor)

In [5]:
type(b)

torch.Tensor

In [6]:
import numpy as np

a=np.random.normal((2,3))
torch.tensor(a)

tensor([2.4332, 1.4238], dtype=torch.float64)

In [7]:
b=torch.tensor(a)
c=torch.ones_like(b)   # 元素都为1  尺度一致
c

tensor([1., 1.], dtype=torch.float64)

In [8]:
d=torch.zeros_like(b)
e=torch.rand_like(b)
d,e

(tensor([0., 0.], dtype=torch.float64),
 tensor([0.2031, 0.6107], dtype=torch.float64))

In [9]:
a=torch.rand([2,2])
a.dtype , a.shape,a.device

(torch.float32, torch.Size([2, 2]), device(type='cpu'))

# Operations on Tensors
including arithmetic,linear algebra,matrix manipulation(transposing,indexing,slicing),sampling and .......

In [10]:
torch.is_tensor(a)

True

In [11]:
a=torch.tensor(1.0)
a

tensor(1.)

In [12]:
a=torch.tensor(0)
torch.is_nonzero(a)

False

In [13]:
a=torch.rand([2,2])
torch.numel(a),a,a.shape

(4,
 tensor([[0.2334, 0.5810],
         [0.4081, 0.3104]]),
 torch.Size([2, 2]))

In [14]:
a=torch.zeros([5,5])
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
a=torch.ones_like(a)
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [16]:
torch.arange(5)
#表示[start,5）  start=0   step默认为1
torch.arange

<function torch._VariableFunctionsClass.arange>

In [17]:
torch.range(start=0,end=5)

/tmp/ipython-input-17-3156877855.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0,end=5)


tensor([0., 1., 2., 3., 4., 5.])

In [18]:
torch.range(0,5)

/tmp/ipython-input-18-1393396694.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [19]:
for i in torch.arange(10):
  print(i)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)


In [20]:
torch.eye(4)  # 不传入第二个参数  就表示为方阵

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [21]:
torch.full([2,2],5)   #size,填充的数

tensor([[5, 5],
        [5, 5]])

In [22]:
a=torch.rand([2,2])
b=torch.rand([2,3])
a,b

(tensor([[0.3481, 0.8553],
         [0.0473, 0.5093]]),
 tensor([[0.1973, 0.8508, 0.1782],
         [0.4265, 0.9506, 0.4080]]))

In [23]:
torch.cat([a,b],dim=1)    #连接tensor

tensor([[0.3481, 0.8553, 0.1973, 0.8508, 0.1782],
        [0.0473, 0.5093, 0.4265, 0.9506, 0.4080]])

In [24]:
b=torch.rand(3,2)

In [25]:
torch.cat([a,b],dim=0)

tensor([[0.3481, 0.8553],
        [0.0473, 0.5093],
        [0.8394, 0.3159],
        [0.0714, 0.7395],
        [0.4149, 0.0693]])

In [26]:
b=torch.rand([3,2])
c,d=torch.chunk(b,chunks=2)
c,d

(tensor([[0.1278, 0.8825],
         [0.4779, 0.5184]]),
 tensor([[0.9989, 0.0316]]))

In [27]:
# gather

# reshape  元素值和顺序不变   变一下格式
a=torch.arange(4.)
torch.reshape(a,(2,2))
a

tensor([0., 1., 2., 3.])

In [28]:
src=torch.arange(1,11).reshape((2,5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [31]:
b=torch.rand([3,2])
b

tensor([[0.6808, 0.2473],
        [0.1094, 0.6609],
        [0.4199, 0.3862]])

In [34]:
torch.reshape(b,[3,1,2])


tensor([[[0.6808, 0.2473]],

        [[0.1094, 0.6609]],

        [[0.4199, 0.3862]]])

In [35]:
torch.squeeze(torch.reshape(b,[3,1,2]))  #squeeze 去除维度为1的   3*1*2->3*2

tensor([[0.6808, 0.2473],
        [0.1094, 0.6609],
        [0.4199, 0.3862]])

In [36]:
torch.reshape(b,[3,1,2,1,1])

tensor([[[[[0.6808]],

          [[0.2473]]]],



        [[[[0.1094]],

          [[0.6609]]]],



        [[[[0.4199]],

          [[0.3862]]]]])

In [39]:
torch.squeeze(torch.reshape(b,[3,1,2,1,1]),dim=3).shape

torch.Size([3, 1, 2, 1])

In [42]:
# stack
a=torch.rand([3,2])
torch.stack([a,b])

tensor([[[0.2419, 0.7270],
         [0.0712, 0.2873],
         [0.7066, 0.1947]],

        [[0.6808, 0.2473],
         [0.1094, 0.6609],
         [0.4199, 0.3862]]])

In [43]:
torch.stack([a,b]).shape    #3*2 和 3*2的在新的维度上叠加

torch.Size([2, 3, 2])

# Tensor Attributes
## Torch datatype
float32  表示浮点数    单精度浮点格式
32比特为三个部分：
- sign bit
- Exponent width
- Significant precision

In [44]:
b

tensor([[0.6808, 0.2473],
        [0.1094, 0.6609],
        [0.4199, 0.3862]])

In [45]:
src=torch.tensor([[4,3,5],[6,7,8]])
torch.take(src,torch.tensor([0,2,5]))   # 类似index索引


tensor([4, 5, 8])

In [48]:
# torch.tile

# torch.transpose
x=torch.rand(2,3)
x=torch.rand([2,3])
x

tensor([[0.3416, 0.1708, 0.0711],
        [0.8116, 0.2540, 0.6047]])

In [51]:
x.shape
x=torch.transpose(x,0,1)
x   #转置

tensor([[0.3416, 0.8116],
        [0.1708, 0.2540],
        [0.0711, 0.6047]])

In [52]:
torch.unbind(x,dim=0)   #分解

(tensor([0.3416, 0.8116]), tensor([0.1708, 0.2540]), tensor([0.0711, 0.6047]))

In [53]:
# torch.where  根据条件进行判断
x=torch.randn(3,2)  # rand->0-1之间【0，1）    randn 高斯分布
y=torch.ones(3,2)
x

tensor([[-0.5435,  0.2664],
        [-0.4311, -0.3641],
        [-0.9863, -0.5875]])

In [54]:
torch.where(x>0,x,y)  #通过这样一个条件判断  形成mask的效果

tensor([[1.0000, 0.2664],
        [1.0000, 1.0000],
        [1.0000, 1.0000]])

In [ ]:
# 随机种子  对cpu gpu都可用
# torch.manual_seed     # 固定随机种子 确定的随机数   保证模型可复现

# 伯努利概率   normal  正态分布

In [55]:
torch.normal(2,3,size=(1,4))
# 均值为2 方差为3  采样的为1*4的

tensor([[ 2.1503, -1.7141,  5.4363, -0.1373]])

In [56]:
torch.randperm(4)  #随机的数

tensor([2, 0, 1, 3])