<a href="https://colab.research.google.com/github/6RobinLiu/PytorchLearn/blob/main/Tensorlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
pip install torch

In [3]:
import torch

a=[1,2,3.]
type(a)

list

In [4]:
b=torch.tensor(a)
b

tensor([1., 2., 3.])

In [5]:
b.dtype,type(b)

(torch.float32, torch.Tensor)

In [6]:
type(b)

torch.Tensor

In [7]:
import numpy as np

a=np.random.normal((2,3))
torch.tensor(a)

tensor([0.9697, 1.5423], dtype=torch.float64)

In [8]:
b=torch.tensor(a)
c=torch.ones_like(b)   # 元素都为1  尺度一致
c

tensor([1., 1.], dtype=torch.float64)

In [9]:
d=torch.zeros_like(b)
e=torch.rand_like(b)
d,e

(tensor([0., 0.], dtype=torch.float64),
 tensor([0.4020, 0.7901], dtype=torch.float64))

In [10]:
a=torch.rand([2,2])
a.dtype , a.shape,a.device

(torch.float32, torch.Size([2, 2]), device(type='cpu'))

# Operations on Tensors
including arithmetic,linear algebra,matrix manipulation(transposing,indexing,slicing),sampling and .......

In [11]:
torch.is_tensor(a)

True

In [12]:
a=torch.tensor(1.0)
a

tensor(1.)

In [13]:
a=torch.tensor(0)
torch.is_nonzero(a)

False

In [14]:
a=torch.rand([2,2])
torch.numel(a),a,a.shape

(4,
 tensor([[0.9521, 0.1130],
         [0.8094, 0.1314]]),
 torch.Size([2, 2]))

In [15]:
a=torch.zeros([5,5])
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [16]:
a=torch.ones_like(a)
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [17]:
torch.arange(5)
#表示[start,5）  start=0   step默认为1
torch.arange

<function torch._VariableFunctionsClass.arange>

In [18]:
torch.range(start=0,end=5)

/tmp/ipython-input-18-3156877855.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0,end=5)


tensor([0., 1., 2., 3., 4., 5.])

In [19]:
torch.range(0,5)

/tmp/ipython-input-19-1393396694.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [20]:
for i in torch.arange(10):
  print(i)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)


In [21]:
torch.eye(4)  # 不传入第二个参数  就表示为方阵

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [22]:
torch.full([2,2],5)   #size,填充的数

tensor([[5, 5],
        [5, 5]])

In [23]:
a=torch.rand([2,2])
b=torch.rand([2,3])
a,b

(tensor([[0.3073, 0.5617],
         [0.9589, 0.3842]]),
 tensor([[0.8025, 0.1960, 0.3161],
         [0.9034, 0.8123, 0.4803]]))

In [24]:
torch.cat([a,b],dim=1)    #连接tensor

tensor([[0.3073, 0.5617, 0.8025, 0.1960, 0.3161],
        [0.9589, 0.3842, 0.9034, 0.8123, 0.4803]])

In [25]:
b=torch.rand(3,2)

In [26]:
torch.cat([a,b],dim=0)

tensor([[0.3073, 0.5617],
        [0.9589, 0.3842],
        [0.5350, 0.6359],
        [0.2478, 0.0191],
        [0.2983, 0.0682]])

In [28]:
b=torch.rand([3,2])
c,d=torch.chunk(b,chunks=2)
c,d

(tensor([[0.2992, 0.9843],
         [0.0955, 0.4722]]),
 tensor([[0.2734, 0.0173]]))

In [9]:
# gather

# reshape  元素值和顺序不变   变一下格式
a=torch.arange(4.)
torch.reshape(a,(2,2))
a

NameError: name 'torch' is not defined